import { Balance, VanillaRuntimeModules } from "@proto-kit/library";
import { ModulesConfig } from "@proto-kit/common";
import { PublicKey } from "o1js";

import { Balances } from "./modules/balances";
import { Withdrawals } from "./modules/withdrawals";
import { DevelopmentYield } from "./modules/developmentYield";
import { MinaliaTreasury } from "./modules/treasury";
import { MinaliaLedger } from "./modules/ledger";
import { MinaliaUnitRegistry } from "./modules/unitRegistry";
import { MinaliaTax } from "./modules/tax";
import { MinaliaSales } from "./modules/sales";
import { MinaliaDevelopmentRegistry } from "./modules/developmentRegistry";

// ---------------------------------------------------------------------------
// Minalia chain role public keys.
//
// Three independent roles, no role can rotate another:
//
//   DEPLOYER (1 key) - chain operator. Bootstraps the chain at genesis
//     (assigns ministers, registers units, sets tax config). Kept alive
//     for rare governance ops (e.g. changing tax rate).
//
//   KING (1 key) - collects currency-exchange commission into the king
//     vault. Unrelated to ministers in the security hierarchy. Future:
//     area-level spending of king vault funds (TBD).
//
//   MINISTER x 20 - one per Luminaea district. Each minister key signs
//     their own district's tax collection, dev management, manager
//     assignment. Bound permanently to their district. Immutable after
//     bootstrap by design - there is no on-chain rotation path.
//
// These are PUBLIC keys; safe to commit. The corresponding private keys
// were generated by scripts/generate-minalia-keys.mjs on 2026-05-25 and
// live in minalia-keys.env (gitignored). They are split across the
// deployer script, king-backend (currency exchange), and minister-cron
// (tax + dev mgmt) processes as needed.
//
// Changing these constants requires a chain restart from genesis.
// ---------------------------------------------------------------------------

export const DEPLOYER_PUB = PublicKey.fromBase58(
  "B62qmuPAxaofwbq6DLZStTH2gMR9gjVtfJtHrsjFXP25PTXCPzRWJak",
);

export const KING_PUB = PublicKey.fromBase58(
  "B62qpe6e9wrt9ywcpX6sonJN2jsKFh9fcDwUUi1uoiGDtBqMiAV2ebV",
);

export interface MinisterPubEntry {
  territoryCode: string;
  pubKey: PublicKey;
}

export const MINISTER_PUBS: ReadonlyArray<MinisterPubEntry> = [
  { territoryCode: "LUM-01", pubKey: PublicKey.fromBase58("B62qjdp2znewGW9cBKT3d8ef3qDHydDKJwo1XyRMeFx4HySnzaAFM8y") },
  { territoryCode: "LUM-02", pubKey: PublicKey.fromBase58("B62qiWr7xdcPGAYrpvme9XjYB8gwxSAamLCtDx61Bcng1xfKBMpvyNh") },
  { territoryCode: "LUM-03", pubKey: PublicKey.fromBase58("B62qj3iPotqCbUif6bnhvKTdyWtHAgqPDN41EnEvM7rfAANnKF2jaiX") },
  { territoryCode: "LUM-04", pubKey: PublicKey.fromBase58("B62qpwTnEDfVKbhGwgSjpVXy7M1885Ka3CbgeNjP4EN2ghXFWgyN3GY") },
  { territoryCode: "LUM-05", pubKey: PublicKey.fromBase58("B62qm4xaC8XUUstGFAm9NCUzJTMU6KAsP8xeyLqWgSP2nN2hRBkw1CD") },
  { territoryCode: "LUM-06", pubKey: PublicKey.fromBase58("B62qnKHE2YYKhXdV9TxGYPDuwLzh2toNS98DTgMk7UUVBwAqj8CCFJz") },
  { territoryCode: "LUM-07", pubKey: PublicKey.fromBase58("B62qqDkhKEs7NuqUAFrtWKjwvMvXQvHafKqguWqwGfbNRW6uSaQgM44") },
  { territoryCode: "LUM-08", pubKey: PublicKey.fromBase58("B62qnknEVt7TkkzSZrrdHc23oCT39obS9EaNY9ZukVnExNPisyYvQH7") },
  { territoryCode: "LUM-09", pubKey: PublicKey.fromBase58("B62qkgy3nEw6vrtcXCv9YukdjLriKZV8R81yrN3ek5EyhU5MJMLzfVs") },
  { territoryCode: "LUM-10", pubKey: PublicKey.fromBase58("B62qrMTA5KJmmnwTC6heNeGF4fJDsUMHhoJVtePbgKS2UPM39F9R2YT") },
  { territoryCode: "LUM-11", pubKey: PublicKey.fromBase58("B62qkLNGrFkSXuXYoGGQk3Ujbogf9w2L587Un6HypgfV31B9tdvLaRB") },
  { territoryCode: "LUM-12", pubKey: PublicKey.fromBase58("B62qjMZLZMsZQ73DZkXZNFSNMvACX9yVGcX5nuU6zLQrcUcg2Wc9Y4Y") },
  { territoryCode: "LUM-13", pubKey: PublicKey.fromBase58("B62qifALTRbKXZzsTAacQxx9Xg4qJm5U6F595uf5cHxrxCzCSfyePcX") },
  { territoryCode: "LUM-14", pubKey: PublicKey.fromBase58("B62qkBXmcXYaj6ZqMpr6QpEHx9ehieuCJfyucfuYweNF9Rss6dxf3YH") },
  { territoryCode: "LUM-15", pubKey: PublicKey.fromBase58("B62qpphfx7KzLmJ1PrJYkPYWoxNET8Yw6WCg4ckY6u2QcJevLJFSNCL") },
  { territoryCode: "LUM-16", pubKey: PublicKey.fromBase58("B62qp9daC8eXrTapY2Hyh7ScgdFArUnN9SnJxLPYy2TzgCfBfLubRWH") },
  { territoryCode: "LUM-17", pubKey: PublicKey.fromBase58("B62qmEpJFsVRGP3juafXGdtahAEFrBkySjhsZz4V9fwsHNqoeisYpSc") },
  { territoryCode: "LUM-18", pubKey: PublicKey.fromBase58("B62qrLUJKipWdrPxWu9GYciKSNTZTpVj22ijxGYzq7b8tNtWr7nEP9e") },
  { territoryCode: "LUM-19", pubKey: PublicKey.fromBase58("B62qkq9u95DGEe1pyjGXBXqz1qsv9nd3KZ7pT2xmGpRz1DYSePJZXL7") },
  { territoryCode: "LUM-20", pubKey: PublicKey.fromBase58("B62qjxtNSqiKNKdfUE5BpcoQtnqogYv4vQxLD9vdyBpjvx8ALSJx63n") },
];

// ---------------------------------------------------------------------------
// Runtime module wiring.
//
// Authority assignments (will be enforced as the module migration proceeds):
//   - Treasury.mint/burn/setSupplyCap/forceTransfer-from-king -> KING_PUB
//   - UnitRegistry.assignMinister/registerUnit/transferUnit   -> DEPLOYER_PUB
//   - Tax.setTaxConfig                                        -> DEPLOYER_PUB
//   - Tax.chargeTax (per unit)                                -> minister-of-territory
//   - DevelopmentRegistry.* (per unit)                        -> minister-of-territory
//
// Per-minister authority is resolved at runtime via UnitRegistry, not from
// genesis config (Protokit configs are scalar-only; no StateMap seeding).
// ---------------------------------------------------------------------------

export const modules = VanillaRuntimeModules.with({
  Balances,
  Withdrawals,
  DevelopmentYield,
  MinaliaTreasury,
  MinaliaLedger,
  MinaliaUnitRegistry,
  MinaliaTax,
  MinaliaSales,
  MinaliaDevelopmentRegistry,
});

export const config: ModulesConfig<typeof modules> = {
  Balances: {
    totalSupply: Balance.from(10_000 * 1e9),
  },
  Withdrawals: {},
  DevelopmentYield: {},
  MinaliaTreasury: {
    authority: KING_PUB,
  },
  MinaliaLedger: {},
  MinaliaUnitRegistry: {
    authority: DEPLOYER_PUB,
  },
  MinaliaTax: {
    authority: DEPLOYER_PUB,
  },
  MinaliaSales: {},
  MinaliaDevelopmentRegistry: {},
};

export default {
  modules,
  config,
};
